Repository honeycombio/honeytail, pull requests merged in 2021-11, with the labels that each got.

#226 Parse trace data from SQL comments
  parsers/postgresql/postgresql.go
  parsers/postgresql/postgresql_test.go
Labels: type: enhancement, version: bump minor

#228 Prepare v1.6.0 release
  CHANGELOG.md
Labels: type: maintenance, version: bump minor

#230 Update install docs for modern go versions
  README.md
Labels: version: no bump, type: documentation

#231 docs: add config usage to readme
  README.md
Labels: version: no bump, type: documentation

#233 Update dependabot to monthly
  .github/dependabot.yml
Labels: type: maintenance, version: no bump, merge at will
