Repository honeycombio/honeytail, pull requests merged in 2022-11, with the labels that each got.

#281 Prep v1.8.2
  CHANGELOG.md
Labels: version: bump patch, type: maintenance

#282 ci: validate PR title
  .github/workflows/validate-pr-title.yml
Labels: type: maintenance, no-changelog, version: no-bump

#283 ci: update validate PR title workflow
  .github/workflows/validate-pr-title.yml
Labels: type: enhancement, no-changelog, version: no-bump
